### ISSUE TITLE
Some common template for Schedule, Sponsors, and FAQ?

### ISSUE THREAD

**Issue by kevinmonisit** [HackRU/frontendv2#12]
<img width="405" alt="image" src="https://github.com/HackRU/frontendv2/assets/7038712/ac968643-c9d6-409f-9bd7-eff77c3e9269">

Looks like there's some pattern that can be standardized for these simpler components (in contrast to About and Hero)

**Comment by bhivam** [comment]
@kevinmonisit should we just do a component that has title on top and content on bottom?

**Comment by kevinmonisit** [comment]
yea we could do that. there's that green bar at the bottom of these sections so you could include that in the common component.
