### ISSUE TITLE
Make Login look good 

### ISSUE THREAD

**Issue by avsomers25** [HackRU/frontendv2#40]
The current login page looks like this 
<img width="502" alt="Login" src="https://github.com/HackRU/frontendv2/assets/67980093/afc84fba-33b9-40df-ae71-782f060b7988">
this isn't great and should be updated to be more inline with the theming across the website, currently the login page is only implemented on the branch 7-create-a-hacker-dashboard

**Comment by kevinmonisit** [comment]
<img width="1219" alt="image" src="https://github.com/HackRU/frontendv2/assets/7038712/cf804d1d-5ee2-41f4-91d7-d8b52339f80d">

Possibly use this ^^? from the assets. just place it in there
